export const CHANGE_TOKEN = 'change_login_token'
export const CHANGE_USER_INFO = 'change_user_info'
export const CHANGE_USER_MENUS = 'change_user_menus'
export const CHANGE_PERMISSIONS = 'change_pdrmissions'
export const CHANGE_ROUTER = 'change_router'
